### ISSUE TITLE
Harden File Read From Symbolic Links

### ISSUE THREAD

**Issue by zakuArbor** [Sxx125/proxyAuth#78]
## Purpose
* previous change #47 tried to address preventing symbolic link attacks but it is still vulnerable to TOCTOU and I assume hardlinks as well
* **inspiration:** https://lwn.net/Articles/939217/
    * `That open() call also uses the O_NOFOLLOW flag`
    *  `however, could open the door to a time-of-check-to-time-of-use vulnerability` 
* **source:** https://wiki.sei.cmu.edu/confluence/display/c/POS01-C.+Check+for+the+existence+of+links+when+dealing+with+files
## Tasks/Goals
- [ ] Open file with nofollow flag
- [ ] Check if file has been tampered
- [ ] Prevent hard links

## Summary
*To fill out once the issue is to be closed. Give a short summary of the changes you made to implement or fix an issue*

**Comment by zakuArbor** [comment]
Checkout https://wiki.sei.cmu.edu/confluence/display/c/POS35-C.+Avoid+race+conditions+while+checking+for+the+existence+of+a+symbolic+link

Existing method is insufficient. Think about using `open` instead of `fopen`
